---
title: "Model"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
data_train <- read.csv("data-train.csv")
data_test <- read.csv("data-test.csv")
```

##Data Cleaning

```{r}
# Change Fr and Re to categorical
data_train$Fr <- as.factor(data_train$Fr)
data_train$Re <- as.factor(data_train$Re)

```

##Linear Model

```{r}
#lm1 <- lm(cbind(R_moment_1, R_moment_2, R_moment_3, R_moment_4) ~ St + Re + Fr, data = data_train)
lm_moment1 <- lm(R_moment_1 ~ St + Re + Fr, data = data_train)
lm_moment2 <- lm(R_moment_2 ~ St + Re + Fr, data = data_train)
lm_moment3 <- lm(R_moment_3 ~ St + Re + Fr, data = data_train)
lm_moment4 <- lm(R_moment_4 ~ St + Re + Fr, data = data_train)

summary(lm_moment1)
summary(lm_moment2)
summary(lm_moment3)
summary(lm_moment4)

```

```{r}
plot(lm_moment1)

```
```{r}
adjusted_lm_moment1 <- lm(log(R_moment_1) ~ poly(St, 2) * Re * Fr, data = data_train) #Make St quadratic
summary(adjusted_lm_moment1)
par(mfrow = c(2,2))
plot(adjusted_lm_moment1)

#note: log response
#The Q–Q plot for the adjusted model (with quadratic St and interactions) indicates that while the central residuals are approximately normal, several extreme points deviate substantially from the expected line. This suggests the presence of heavy tails and influential cases, likely arising from extreme parameter settings. A log transformation of the response or a robust regression approach can mitigate these effects and improve model normality.

#note: ploy term
#Initial diagnostic plots revealed a systematic pattern in the residuals, suggesting that the effect of the Stokes number (St) on the mean cluster volume was nonlinear. To capture this curvature, we included a second-order polynomial term, poly(St, 2), which adds both linear and quadratic components of St to the model. This adjustment improves model flexibility while maintaining interpretability.

##TODO: Find which interaction effects are significant
```
#remove insignificant interaction effects
```{r}
adjusted_lm_moment1 <- lm(log(R_moment_1) ~ poly(St, 2) * Fr + Re:Fr, data = data_train) #Make St quadratic
summary(adjusted_lm_moment1)
```


```{r}
plot(lm_moment2)
```


```{r}
adjusted_lm_moment2 <- lm(R_moment_2 ~ poly(St, 2) * Re * Fr, data = data_train) #Make St quadratic
summary(adjusted_lm_moment2)
plot(adjusted_lm_moment2)
```

```{r}
plot(lm_moment3)
```
```{r}
adjusted_lm_moment3 <- lm(R_moment_3 ~ poly(St, 2) * Re * Fr, data = data_train) #Make St quadratic
summary(adjusted_lm_moment3)
plot(adjusted_lm_moment3)
```

```{r}
plot(lm_moment4)
```
```{r}
adjusted_lm_moment4 <- lm(R_moment_4 ~ poly(St, 2) * Re * Fr, data = data_train) #Make St quadratic
summary(adjusted_lm_moment4)
plot(adjusted_lm_moment4)
```


